Repository THIP-TextHip/THIP-Android, pull requests merged in 2025-07, with the labels that each got.

#32 [UI] 모임방 페이지 구현 완료
  app/src/main/java/com/texthip/thip/ui/common/buttons/GroupVoteButton.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardChat.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardCommentGroup.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardNote.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardVote.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/CommentTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/header/ProfileBar.kt
  app/src/main/java/com/texthip/thip/ui/common/header/ProfileBarWithDate.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/BookTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/DefaultTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/FeedListTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/GradationTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/InputTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/LeftNameTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/LogoTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/view/CountingBar.kt
  app/src/main/java/com/texthip/thip/ui/group/room/component/GroupRoomBody.kt
  app/src/main/java/com/texthip/thip/ui/group/room/component/GroupRoomHeader.kt
  app/src/main/java/com/texthip/thip/ui/group/room/component/GroupRoomMatesList.kt
  app/src/main/java/com/texthip/thip/ui/group/room/mock/GroupRoomBodyData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/mock/GroupRoomChatData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/mock/GroupRoomHeaderData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/mock/GroupRoomMateData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/mock/VoteData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomChatScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomMatesScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/theme/Color.kt
  app/src/main/res/drawable/img_group_room.png
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🍀 refactor, 🐱 나은, ✅ OK merge

#30 [UI] 모임 페이지 구현 완료
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/texthip/thip/ui/common/buttons/OptionChipButton.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardAlarm.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardInputBook.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardItemRoom.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardItemRoomSmall.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardRoomBook.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/FormTextFieldDefault.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GenreChipRow.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupDeadlineRoomSection.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupMainCard.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupMyRoomFilterRow.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupMySectionHeader.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupPager.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupSearchTextField.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/SimplePagerIndicator.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupBookData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupBottomButtonType.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupCardData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupCardItemRoomData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupRoomData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupRoomSectionData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupMyScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/myPage/MyPageScreen.kt
  app/src/main/java/com/texthip/thip/ui/navigator/MainNavHost.kt
  app/src/main/java/com/texthip/thip/ui/theme/Color.kt
  app/src/main/res/drawable/bookcover_sample_small.png
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: 🎨 UI, 🍀 refactor, 🐻 규빈, ✅ OK merge

#38 [UI] 기록장 화면에 필요한 컴포넌트
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/texthip/thip/ui/common/bottomsheet/MenuBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/ActionBarButton.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/FilterButton.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/FilterChipButton.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/FormButton.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/OptionChipButton.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/SendButton.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/PageTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/header/HeaderMenuBarTab.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/FilterHeaderSection.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/TextCommentCard.kt
  app/src/main/java/com/texthip/thip/ui/group/note/mock/CommentData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomScreen.kt
  app/src/main/res/drawable/ic_heart.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🍀 refactor, 🐱 나은, ✅ OK merge

#39 [UI] 모임방 만들기 페이지 구현 완료
  .idea/deviceManager.xml
  .idea/misc.xml
  app/src/main/java/com/texthip/thip/ui/common/bottomsheet/CustomBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/GenreChipRow.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardBookSearch.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/SearchBookTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/WarningTextField.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupBookListWithScrollbar.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupBookSearchBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupDatePicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupEmptyBookSheetContent.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupInputField.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupMemberLimitPicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupRoomDurationPicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupSelectBook.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupWheelPicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/SectionDivider.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/mock/GroupBookData.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/mock/GroupMakeRoomRequest.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/mock/GroupMakeRoomUiState.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/screen/GroupMakeRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/screen/GroupRegisterBookScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/util/WheelPickerDisplayUtils.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/viewmodel/GroupMakeRoomViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupDeadlineRoomSection.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupMainCard.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupPager.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupMyScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/myPage/screen/MyPageScreen.kt
  app/src/main/res/drawable/ic_notice.xml
  app/src/main/res/drawable/ic_notification.xml
  app/src/main/res/drawable/ic_x_circle_grey.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🐻 규빈, ✅ OK merge

#42 [UI] 공통 알림 페이지 구현 완료
  .idea/misc.xml
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/component/AlarmFilterRow.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/mock/AlarmItem.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/screen/AlarmScreen.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardAlarm.kt
  app/src/main/java/com/texthip/thip/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🐻 규빈, ✅ OK merge

#41 [UI] 로그인/ 스플래시/ 홈-내 구독 리스트 구현
  .idea/gradle.xml
  app/src/main/java/com/texthip/thip/ui/booksearch/screen/BookSearchScreen.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/ActionMediumButton.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/WarningTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/header/AuthorHeader.kt
  app/src/main/java/com/texthip/thip/ui/common/header/ProfileBar.kt
  app/src/main/java/com/texthip/thip/ui/common/modal/ToastWithDate.kt
  app/src/main/java/com/texthip/thip/ui/feed/component/MySubscriptionList.kt
  app/src/main/java/com/texthip/thip/ui/feed/mock/MySubscriptionData.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/FeedScreen.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/MySubscriptionListScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/MypageSaveBook.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/MypageSaveFeed.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/RoleCard.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/SavedFeedCard.kt
  app/src/main/java/com/texthip/thip/ui/mypage/mock/BookItem.kt
  app/src/main/java/com/texthip/thip/ui/mypage/mock/FeedItem.kt
  app/src/main/java/com/texthip/thip/ui/mypage/mock/ReactionItem.kt
  app/src/main/java/com/texthip/thip/ui/mypage/mock/RoleItem.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageEditScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageLeavethipCompleteScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageLeavethipScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageNotificationEditScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageReactionScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageSaveScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/viewmodel/SavedBookViewModel.kt
  app/src/main/java/com/texthip/thip/ui/mypage/viewmodel/SavedFeedViewModel.kt
  app/src/main/java/com/texthip/thip/ui/navigator/MainNavHost.kt
  app/src/main/java/com/texthip/thip/ui/signin/mock/SignupUserInfo.kt
  app/src/main/java/com/texthip/thip/ui/signin/screen/LoginScreen.kt
  app/src/main/java/com/texthip/thip/ui/signin/screen/SignupDoneScreen.kt
  app/src/main/java/com/texthip/thip/ui/signin/screen/SignupNicknameScreen.kt
  app/src/main/java/com/texthip/thip/ui/signin/screen/SplashScreen.kt
  app/src/main/java/com/texthip/thip/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🍀 refactor, 🐹 주연

#46 [UI] 모임페이지 홈 추가 UI 구현
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  app/src/main/java/com/texthip/thip/ui/common/buttons/GenreChipButton.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/GenreChipRow.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardItemRoom.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardItemRoomSmall.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/SearchBookTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/SingleDigitTextBox.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/WarningTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/modal/ToastWithDate.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/DefaultTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupBookSearchBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupDeadlineRoomSection.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupEmptyCard.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupPager.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupSearchTextField.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupCardItemRoomData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupEmptyResultScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupFilteredSearchResultScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupLiveSearchResultScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupMyScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRecentSearchScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRoomSecretScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupSearchScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupDoneScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/res/drawable/group_room_recruiting.png
  app/src/main/res/drawable/ic_secret_cover.xml
  app/src/main/res/drawable/ic_thip_empty_room.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🍀 refactor, 🐻 규빈, ✅ OK merge

#49 [UI] 기록장 상세 페이지 구현 완료
  app/src/main/java/com/texthip/thip/ui/common/buttons/ExpandableFloatingButton.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/ToggleSwitchButton.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/BookPageTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/BorderedTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/modal/ToolTip.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/OpinionInputSection.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/PageInputSection.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/VoteInputSection.kt
  app/src/main/java/com/texthip/thip/ui/group/note/screen/GroupNoteCreateScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/note/screen/GroupVoteCreateScreen.kt
  app/src/main/res/drawable/ic_x_circle_darkgrey.xml
  app/src/main/res/drawable/ic_x_circle_grey.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🐱 나은, ✅ OK merge

#48 [UI] 책 검색 페이지 화면 구현
  .idea/misc.xml
  app/src/main/java/com/texthip/thip/ui/booksearch/component/BookEmptyResult.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/component/BookFilteredSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/component/BookLiveSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/component/BookRecentSearch.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/mock/BookData.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/mock/DetailBookData.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/screen/BookDetailScreen.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/screen/BookRecruitingScreen.kt
  app/src/main/java/com/texthip/thip/ui/booksearch/screen/BookSearchScreen.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/ActionMediumButton.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardBookList.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardBookSearch.kt
  app/src/main/java/com/texthip/thip/ui/common/modal/InfoPopup.kt
  app/src/main/java/com/texthip/thip/ui/common/screen/RegisterBookScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupEmptyResult.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupFilteredSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupLiveSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupRecentSearch.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRoomSecretScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupSearchScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/navigator/MainNavHost.kt
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🍀 refactor, 🐻 규빈, ✅ OK merge

#54 [UI] 모임방 페이지 QA
  app/src/main/java/com/texthip/thip/ui/common/cards/CardItemRoom.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardItemRoomSmall.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardRoomBook.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/SearchBookTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/WarningTextField.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupBookListWithScrollbar.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupBookSearchBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupDatePicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupEmptyBookSheetContent.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupMemberLimitPicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupRoomDurationPicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupSelectBook.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupWheelPicker.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/mock/GroupBookData.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/screen/GroupMakeRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupDeadlineRoomSection.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupEmptyResult.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupFilteredSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupLiveSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupMainCard.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupMyRoomFilterRow.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupRecentSearch.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupSearchTextField.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/SimplePagerIndicator.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupMyScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupRoomSecretScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupDoneScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/navigator/MainNavHost.kt
  app/src/main/java/com/texthip/thip/ui/search/component/SearchActiveField.kt
  app/src/main/java/com/texthip/thip/ui/search/component/SearchBookFilteredResult.kt
  app/src/main/java/com/texthip/thip/ui/search/component/SearchEmptyResult.kt
  app/src/main/java/com/texthip/thip/ui/search/component/SearchRecentBook.kt
  app/src/main/java/com/texthip/thip/ui/search/mock/BookData.kt
  app/src/main/java/com/texthip/thip/ui/search/mock/DetailBookData.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookDetailScreen.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookGroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookScreen.kt
  app/src/main/res/drawable/ic_x_circle_grey02.xml
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🍀 refactor, 🐻 규빈, ✅ OK merge

#57 [FEAT] 네비게이션 연결 기초 세팅 완료
  app/build.gradle.kts
  app/src/main/java/com/texthip/thip/MainScreen.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/screen/AlarmScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/screen/GroupMakeRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/viewmodel/GroupMakeRoomViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/viewmodel/GroupViewModel.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageScreen.kt
  app/src/main/java/com/texthip/thip/ui/navigator/BarItem.kt
  app/src/main/java/com/texthip/thip/ui/navigator/BottomNavigationBar.kt
  app/src/main/java/com/texthip/thip/ui/navigator/MainNavHost.kt
  app/src/main/java/com/texthip/thip/ui/navigator/NavBarItems.kt
  app/src/main/java/com/texthip/thip/ui/navigator/Routes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/data/BarItem.kt
  app/src/main/java/com/texthip/thip/ui/navigator/data/NavBarItems.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/CommonNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/FeedNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/GroupNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/MyPageNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/SearchNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/FeedNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/GroupNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/MyPageNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/SearchNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/FeedRoutes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/GroupRoutes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/MyPageRoutes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/Routes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/SearchRoutes.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ feat, 🍀 refactor, 🐻 규빈, ✅ OK merge

#56 [UI] 데이터 없는 페이지들 구현
  app/src/main/java/com/texthip/thip/ui/common/bottomsheet/MenuBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/OptionChipButton.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardCommentGroup.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardVote.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/CommentTextField.kt
  app/src/main/java/com/texthip/thip/ui/common/modal/DialogPopup.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/DefaultTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/CommentBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/CommentSection.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/FilterHeaderSection.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/TextCommentCard.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/VoteCommentCard.kt
  app/src/main/java/com/texthip/thip/ui/group/note/screen/GroupNoteScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/mock/GroupRoomChatData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/mock/VoteData.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomChatScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomRecruitScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomUnlockScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupEmptyResult.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupFilteredSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupLiveSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupRecentSearch.kt
  app/src/main/java/com/texthip/thip/ui/group/search/screen/GroupSearchScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🎨 UI, 🍀 refactor, 🐱 나은, ✅ OK merge
