Repository THIP-TextHip/THIP-Android, pull requests merged in 2025-08, with the labels that each got.

#60 [FEAT] 검색, 모임방 메인 스크린 네비게이션 연결
  app/src/main/java/com/texthip/thip/data/group/repository/GroupRepository.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/screen/AlarmScreen.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/viewmodel/AlarmViewModel.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/SearchBookTextField.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupDeadlineRoomSection.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupSearchTextField.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupCardData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupCardItemRoomData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/mock/GroupRoomData.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupMyScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomRecruitScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupDoneScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupFilteredSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupLiveSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/search/screen/GroupSearchScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/viewmodel/GroupViewModel.kt
  app/src/main/java/com/texthip/thip/ui/navigator/MainNavHost.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/CommonNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/GroupNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/CommonNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/GroupNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/CommonRoutes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/GroupRoutes.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookGroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookScreen.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: ✨ feat, 🍀 refactor, 🐻 규빈, ✅ OK merge

#64 [API] api 연결 세팅
  .idea/compiler.xml
  .idea/gradle.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/texthip/thip/MainActivity.kt
  app/src/main/java/com/texthip/thip/ThipApplication.kt
  app/src/main/java/com/texthip/thip/data/di/NetworkModule.kt
  app/src/main/java/com/texthip/thip/data/di/ServiceModule.kt
  app/src/main/java/com/texthip/thip/data/model/base/ApiResponseHandler.kt
  app/src/main/java/com/texthip/thip/data/model/base/BaseResponse.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: ✨ feat, 🐱 나은, ✅ OK merge

#79 [FEAT] 책 검색 화면 API 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/texthip/thip/data/manager/Genre.kt
  app/src/main/java/com/texthip/thip/data/model/book/request/BookSaveRequest.kt
  app/src/main/java/com/texthip/thip/data/model/book/response/BookDetailResponse.kt
  app/src/main/java/com/texthip/thip/data/model/book/response/BookListResponse.kt
  app/src/main/java/com/texthip/thip/data/model/book/response/BookSaveResponse.kt
  app/src/main/java/com/texthip/thip/data/model/book/response/BookSearchResponse.kt
  app/src/main/java/com/texthip/thip/data/model/book/response/MostSearchedBooksResponse.kt
  app/src/main/java/com/texthip/thip/data/model/book/response/RecentSearchResponse.kt
  app/src/main/java/com/texthip/thip/data/model/book/response/RecruitingRoomsResponse.kt
  app/src/main/java/com/texthip/thip/data/model/group/response/JoinedRoomListResponse.kt
  app/src/main/java/com/texthip/thip/data/repository/BookRepository.kt
  app/src/main/java/com/texthip/thip/data/repository/GroupRepository.kt
  app/src/main/java/com/texthip/thip/data/service/BookService.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/GenreChipButton.kt
  app/src/main/java/com/texthip/thip/ui/common/screen/RegisterBookScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/done/screen/GroupDoneScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/done/viewmodel/GroupDoneViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupSelectBook.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/screen/GroupMakeRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/viewmodel/GroupMakeRoomUiState.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/viewmodel/GroupMakeRoomViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupMainCard.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupPager.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/screen/GroupMyScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/viewmodel/GroupMyViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomRecruitScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/viewmodel/GroupViewModel.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/CommonNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/GroupNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/SearchNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/CommonNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/GroupNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/SearchNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/CommonRoutes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/GroupRoutes.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/SearchRoutes.kt
  app/src/main/java/com/texthip/thip/ui/search/component/SearchActiveField.kt
  app/src/main/java/com/texthip/thip/ui/search/component/SearchBookFilteredResult.kt
  app/src/main/java/com/texthip/thip/ui/search/mock/BookData.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookDetailScreen.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookGroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookScreen.kt
  app/src/main/java/com/texthip/thip/ui/search/viewmodel/BookDetailViewModel.kt
  app/src/main/java/com/texthip/thip/ui/search/viewmodel/SearchBookGroupViewModel.kt
  app/src/main/java/com/texthip/thip/ui/search/viewmodel/SearchBookUiState.kt
  app/src/main/java/com/texthip/thip/ui/search/viewmodel/SearchBookViewModel.kt
  app/src/main/res/xml/network_security_config.xml
Labels: ✨ feat, 🍀 refactor, 🐻 규빈, ✅ OK merge

#82 [API] 내 팔로잉 목록 조회 API 연동
  app/src/main/java/com/texthip/thip/data/di/ServiceModule.kt
  app/src/main/java/com/texthip/thip/data/model/users/MyFollowingsResponse.kt
  app/src/main/java/com/texthip/thip/data/repository/UserRepository.kt
  app/src/main/java/com/texthip/thip/data/service/UserService.kt
  app/src/main/java/com/texthip/thip/ui/common/header/AuthorHeader.kt
  app/src/main/java/com/texthip/thip/ui/feed/component/MySubscribelistBar.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/FeedScreen.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/MySubscriptionListScreen.kt
  app/src/main/java/com/texthip/thip/ui/feed/viewmodel/MySubscriptionViewModel.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/FeedNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/FeedNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/FeedRoutes.kt
  app/src/main/java/com/texthip/thip/utils/color/HexToColor.kt
Labels: ✨ feat, 🐹 주연

#84 [API] 댓글 관련 api 연결 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/texthip/thip/data/di/ServiceModule.kt
  app/src/main/java/com/texthip/thip/data/model/comments/request/CommentsCreateRequest.kt
  app/src/main/java/com/texthip/thip/data/model/comments/request/CommentsLikesRequest.kt
  app/src/main/java/com/texthip/thip/data/model/comments/response/CommentsCreateResponse.kt
  app/src/main/java/com/texthip/thip/data/model/comments/response/CommentsLikesResponse.kt
  app/src/main/java/com/texthip/thip/data/model/comments/response/CommentsResponse.kt
  app/src/main/java/com/texthip/thip/data/model/rooms/response/RoomsPlayingResponse.kt
  app/src/main/java/com/texthip/thip/data/model/rooms/response/RoomsUsersResponse.kt
  app/src/main/java/com/texthip/thip/data/repository/CommentsRepository.kt
  app/src/main/java/com/texthip/thip/data/service/CommentsService.kt
  app/src/main/java/com/texthip/thip/ui/common/header/ProfileBar.kt
  app/src/main/java/com/texthip/thip/ui/common/header/ProfileBarFeed.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/FeedCommentScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/CommentBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/CommentItem.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/CommentSection.kt
  app/src/main/java/com/texthip/thip/ui/group/note/component/ReplyItem.kt
  app/src/main/java/com/texthip/thip/ui/group/note/screen/GroupNoteScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/note/viewmodel/CommentsViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/room/component/GroupRoomHeader.kt
  app/src/main/java/com/texthip/thip/ui/group/room/component/GroupRoomMatesList.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomMatesScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/GroupNavigation.kt
  app/src/main/java/com/texthip/thip/utils/color/HexToColor.kt
  app/src/main/java/com/texthip/thip/utils/rooms/AdvancedImePadding.kt
Labels: ✨ feat, 🍀 refactor, 🐱 나은, ✅ OK merge

#88 [API] 피드 작성 구현
  app/src/main/java/com/texthip/thip/data/di/ServiceModule.kt
  app/src/main/java/com/texthip/thip/data/model/feed/request/CreateFeedRequest.kt
  app/src/main/java/com/texthip/thip/data/model/feed/response/CreateFeedResponse.kt
  app/src/main/java/com/texthip/thip/data/model/feed/response/FeedWriteInfoResponse.kt
  app/src/main/java/com/texthip/thip/data/repository/FeedRepository.kt
  app/src/main/java/com/texthip/thip/data/service/FeedService.kt
  app/src/main/java/com/texthip/thip/ui/common/buttons/SubGenreChipRow.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/FeedScreen.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/FeedWriteScreen.kt
  app/src/main/java/com/texthip/thip/ui/feed/viewmodel/FeedWriteUiState.kt
  app/src/main/java/com/texthip/thip/ui/feed/viewmodel/FeedWriteViewModel.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/FeedNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/FeedNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/FeedRoutes.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat, 🐻 규빈, ✅ OK merge

#115 [FEAT] 저장 조회 화면 api 연결
  .gitignore
  .idea/appInsightsSettings.xml
  .idea/misc.xml
  app/src/main/java/com/texthip/thip/data/model/book/response/BookUserSaveResponse.kt
  app/src/main/java/com/texthip/thip/data/repository/BookRepository.kt
  app/src/main/java/com/texthip/thip/data/repository/FeedRepository.kt
  app/src/main/java/com/texthip/thip/data/service/BookService.kt
  app/src/main/java/com/texthip/thip/data/service/FeedService.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardItemRoomSmall.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/DefaultTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/common/topappbar/GradationTopAppBar.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomRecruitScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/room/screen/GroupRoomScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupFilteredSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/group/search/component/GroupLiveSearchResult.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/BookContent.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/FeedContent.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/SavedFeedCard.kt
  app/src/main/java/com/texthip/thip/ui/mypage/mock/BookItem.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageSaveScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/viewmodel/SavedBookViewModel.kt
  app/src/main/java/com/texthip/thip/ui/mypage/viewmodel/SavedFeedViewModel.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/MyPageNavigation.kt
  app/src/main/java/com/texthip/thip/ui/signin/screen/LoginScreen.kt
Labels: ✨ feat, 🍀 refactor, 🐱 나은, ✅ OK merge
