Repository THIP-TextHip/THIP-Android, pull requests merged in 2025-09, with the labels that each got.

#128 [Refactor] 소셜로그인, 회원가입 관련 오류 수정
  .gitignore
  .idea/.gitignore
  app/build.gradle.kts
  app/google-services.json
  app/src/main/java/com/texthip/thip/data/repository/AuthRepository.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageEditScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/java/com/texthip/thip/ui/signin/screen/SignupNicknameScreen.kt
  app/src/main/res/values/strings.xml
Labels: 🍀 refactor, 🐹 주연, ✅ OK merge

#129 [REFACTOR] QA 나머지 수정
  app/src/main/java/com/texthip/thip/ui/common/buttons/GenreChipRow.kt
  app/src/main/java/com/texthip/thip/ui/common/cards/CardInputBook.kt
  app/src/main/java/com/texthip/thip/ui/feed/component/MyFeedCard.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/FeedCommentScreen.kt
  app/src/main/java/com/texthip/thip/ui/feed/viewmodel/FeedWriteViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupSelectBook.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/viewmodel/GroupMakeRoomViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/myroom/component/GroupDeadlineRoomSection.kt
  app/src/main/java/com/texthip/thip/ui/mypage/component/SavedFeedCard.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageScreen.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/FeedNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/SearchNavigation.kt
  app/src/main/java/com/texthip/thip/ui/search/screen/SearchBookDetailScreen.kt
Labels: 🎨 UI, 🍀 refactor, 🐻 규빈, ✅ OK merge

#136 [FEAT] FCM Token 발급, 등록, 푸시알림 기능 구현 및 기타 QA수정
  .idea/appInsightsSettings.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/texthip/thip/MainActivity.kt
  app/src/main/java/com/texthip/thip/MainScreen.kt
  app/src/main/java/com/texthip/thip/ThipApplication.kt
  app/src/main/java/com/texthip/thip/data/di/ServiceModule.kt
  app/src/main/java/com/texthip/thip/data/manager/FcmTokenManager.kt
  app/src/main/java/com/texthip/thip/data/manager/Genre.kt
  app/src/main/java/com/texthip/thip/data/manager/TokenManager.kt
  app/src/main/java/com/texthip/thip/data/model/notification/request/FcmTokenDeleteRequest.kt
  app/src/main/java/com/texthip/thip/data/model/notification/request/FcmTokenRequest.kt
  app/src/main/java/com/texthip/thip/data/model/notification/request/NotificationEnabledRequest.kt
  app/src/main/java/com/texthip/thip/data/model/notification/response/NotificationEnabledResponse.kt
  app/src/main/java/com/texthip/thip/data/repository/BookRepository.kt
  app/src/main/java/com/texthip/thip/data/repository/FeedRepository.kt
  app/src/main/java/com/texthip/thip/data/repository/NotificationRepository.kt
  app/src/main/java/com/texthip/thip/data/repository/RecentSearchRepository.kt
  app/src/main/java/com/texthip/thip/data/repository/RoomsRepository.kt
  app/src/main/java/com/texthip/thip/data/repository/UserRepository.kt
  app/src/main/java/com/texthip/thip/data/service/NotificationService.kt
  app/src/main/java/com/texthip/thip/service/MyFirebaseMessagingService.kt
  app/src/main/java/com/texthip/thip/ui/common/forms/SearchBookTextField.kt
  app/src/main/java/com/texthip/thip/ui/feed/component/MySubscribelistBar.kt
  app/src/main/java/com/texthip/thip/ui/group/makeroom/component/GroupBookSearchBottomSheet.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageLeavethipScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageNotificationEditScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/viewmodel/DeleteAccountViewModel.kt
  app/src/main/java/com/texthip/thip/ui/mypage/viewmodel/MypageNotificationEditViewModel.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/MyPageNavigation.kt
  app/src/main/java/com/texthip/thip/ui/signin/viewmodel/LoginViewModel.kt
  app/src/main/java/com/texthip/thip/ui/signin/viewmodel/SignupViewModel.kt
  app/src/main/java/com/texthip/thip/ui/signin/viewmodel/SplashViewModel.kt
  app/src/main/java/com/texthip/thip/utils/auth/DeviceUtils.kt
  app/src/main/java/com/texthip/thip/utils/image/ImageUploadHelper.kt
  app/src/main/java/com/texthip/thip/utils/permission/NotificationPermissionUtils.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: ✨ feat, 🍀 refactor, 🧹 chore, 🐻 규빈, ✅ OK merge

#141 [FEAT] 알림 센터 API 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/texthip/thip/MainActivity.kt
  app/src/main/java/com/texthip/thip/MainScreen.kt
  app/src/main/java/com/texthip/thip/data/manager/FcmTokenManager.kt
  app/src/main/java/com/texthip/thip/data/model/notification/request/NotificationCheckRequest.kt
  app/src/main/java/com/texthip/thip/data/model/notification/response/NotificationCheckResponse.kt
  app/src/main/java/com/texthip/thip/data/model/notification/response/NotificationListResponse.kt
  app/src/main/java/com/texthip/thip/data/repository/NotificationRepository.kt
  app/src/main/java/com/texthip/thip/data/service/NotificationService.kt
  app/src/main/java/com/texthip/thip/service/MyFirebaseMessagingService.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/component/AlarmFilterRow.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/mock/NotificationType.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/screen/AlarmScreen.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/viewmodel/AlarmUiState.kt
  app/src/main/java/com/texthip/thip/ui/common/alarmpage/viewmodel/AlarmViewModel.kt
  app/src/main/java/com/texthip/thip/ui/feed/screen/FeedScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/note/screen/GroupNoteScreen.kt
  app/src/main/java/com/texthip/thip/ui/group/note/viewmodel/GroupNoteViewModel.kt
  app/src/main/java/com/texthip/thip/ui/group/screen/GroupScreen.kt
  app/src/main/java/com/texthip/thip/ui/mypage/screen/MypageNotificationEditScreen.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/GroupNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/extensions/NotificationNavigationExtensions.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/CommonNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/navigations/GroupNavigation.kt
  app/src/main/java/com/texthip/thip/ui/navigator/routes/GroupRoutes.kt
  app/src/main/res/values/strings.xml
Labels: ✨ feat, 🎨 UI, 🍀 refactor, 🐻 규빈, ✅ OK merge
